#pragma once
#include <SFML/Window.hpp>
#include <SFML/Audio.hpp>
#include "SFML/Graphics.hpp"
#include "iostream"
#include "string"
#include "windows.h"
#include "thread"
#include "fstream"
#include "sstream"
#include <vector>
#include <random>
#include <cstdlib>
#include <string>
#include <iostream>
#include <fstream>
